function skillsMember() {
  return {
    name: 'skills',
    type: 'list',
    message: 'What are your skills?',
    choices: [
      'React',
      'Vue',
      'Angular',
      'Node',
      'Express',
      'MongoDB',
      'MySQL',
      'Postgres',
      'GraphQL',
      'Apollo',
      'REST',
      'TypeScript',
      'JavaScript',
      'Python',
      'Java',
      'C#',
      'C++',
      'C',
      'Ruby',
      'PHP',
      'HTML',
      'CSS',
      'SASS',
      'LESS',
      'Bootstrap',
      'Materialize',
      'Semantic UI',
      'Tailwind CSS',
      'JQuery',
      'D3',
      'Three',
      'Canvas',
      'WebGL',
      'WebRTC',
      'Socket.io',
      'WebSockets',
      'Docker',
      'Kubernetes',
      'AWS',
      'GCP',
      'Azure',
      'Heroku',
      'Netlify',
      'Vercel',
      'CI/CD',
      'Jest',
      'Mocha',
      'Chai',
      'Cypress',
      'Puppeteer',
      'Karma',
      'Protractor',
      'Selenium',
      'Jasmine',
      'React Testing Library',
      'Enzyme',
      'WebdriverIO',
      'Nightwatch',
      'PWA',
      'SPA',
      'SSR',
      'SEO',
      'Accessibility',
      'Performance',
      'Responsive Design',
      'Git',
      'SVN',
      'Mercurial',
      'Agile',
      'Scrum',
      'Kanban',
      'Waterfall',
      'Pair Programming',
      'Mob Programming',
      'Code Review',
      'TDD',
      'BDD',
      'DDD',
      'CI/CD',
      'DevOps',
      'Agile',
      'Scrum',
      'Kanban',
      'Waterfall',
      'Pair Programming',
      'Mob Programming',
      'Code Review',
      'TDD',
      'BDD',
      'DDD',
      'CI/CD',
      'DevOps',
      'Agile',
      'Scrum',
      'Kanban',
      'Waterfall',
      'Pair Programming'
            ],
      };
    }